import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="min-h-screen bg-gray-50">
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className="container mx-auto px-4 py-8">
        <div className="flex justify-center mb-8">
          <ConnectButton />
        </div>

        <h1 className="text-4xl font-bold text-center text-gray-900 mb-8">
          Welcome to{" "}
          <a
            href="https://www.rainbowkit.com"
            className="text-blue-600 hover:text-blue-800"
          >
            RainbowKit
          </a>{" "}
          +{" "}
          <a
            href="https://wagmi.sh"
            className="text-purple-600 hover:text-purple-800"
          >
            wagmi
          </a>{" "}
          +{" "}
          <a
            href="https://nextjs.org"
            className="text-green-600 hover:text-green-800"
          >
            Next.js!
          </a>
        </h1>

        <p className="text-lg text-center text-gray-600 mb-12">
          Get started by editing{" "}
          <code className="bg-gray-200 px-2 py-1 rounded text-sm font-mono">
            pages/index.tsx
          </code>
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <a
            className="block p-6 bg-white rounded-lg shadow-md hover:shadow-lg transition-shadow duration-200"
            href="https://rainbowkit.com"
          >
            <h2 className="text-xl font-semibold text-gray-900 mb-2">
              RainbowKit Documentation &rarr;
            </h2>
            <p className="text-gray-600">
              Learn how to customize your wallet connection flow.
            </p>
          </a>

          <a
            className="block p-6 bg-white rounded-lg shadow-md hover:shadow-lg transition-shadow duration-200"
            href="https://wagmi.sh"
          >
            <h2 className="text-xl font-semibold text-gray-900 mb-2">
              wagmi Documentation &rarr;
            </h2>
            <p className="text-gray-600">
              Learn how to interact with Ethereum.
            </p>
          </a>

          <a
            className="block p-6 bg-white rounded-lg shadow-md hover:shadow-lg transition-shadow duration-200"
            href="https://github.com/rainbow-me/rainbowkit/tree/main/examples"
          >
            <h2 className="text-xl font-semibold text-gray-900 mb-2">
              RainbowKit Examples &rarr;
            </h2>
            <p className="text-gray-600">
              Discover boilerplate example RainbowKit projects.
            </p>
          </a>

          <a
            className="block p-6 bg-white rounded-lg shadow-md hover:shadow-lg transition-shadow duration-200"
            href="https://nextjs.org/docs"
          >
            <h2 className="text-xl font-semibold text-gray-900 mb-2">
              Next.js Documentation &rarr;
            </h2>
            <p className="text-gray-600">
              Find in-depth information about Next.js features and API.
            </p>
          </a>

          <a
            className="block p-6 bg-white rounded-lg shadow-md hover:shadow-lg transition-shadow duration-200"
            href="https://github.com/vercel/next.js/tree/canary/examples"
          >
            <h2 className="text-xl font-semibold text-gray-900 mb-2">
              Next.js Examples &rarr;
            </h2>
            <p className="text-gray-600">
              Discover and deploy boilerplate example Next.js projects.
            </p>
          </a>

          <a
            className="block p-6 bg-white rounded-lg shadow-md hover:shadow-lg transition-shadow duration-200"
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          >
            <h2 className="text-xl font-semibold text-gray-900 mb-2">
              Deploy &rarr;
            </h2>
            <p className="text-gray-600">
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className="text-center py-8 text-gray-600">
        <a
          href="https://rainbow.me"
          rel="noopener noreferrer"
          target="_blank"
          className="hover:text-gray-800"
        >
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
